name: Android CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # - name: Setting output to GITHUB_OUTPUT
    #   id: set_output
    #   run: |
    #     testLocalVar="hello i am local var"
    #     echo "testGlobalVar=$testLocalVar" >> $GITHUB_OUTPUT
    
    # - name: Accessing github output
    #   run: |
    #     echo ${{ steps.set_output.outputs.testGlobalVar }}
    #     echo "concatinating global var ${{ steps.set_output.outputs.testGlobalVar }}"

    - name: Setting output to GITHUB_Summary
      id: set_summary
      run: |
        testLocalVar="hello i am the summary"
        echo "$testLocalVar" >> $GITHUB_STEP_SUMMARY
