name: Android CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  test_file: test_file.html
jobs:
  build_one:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # - name: Setting output to GITHUB_OUTPUT
    #   id: set_output
    #   run: |
    #     testLocalVar="hello i am local var"
    #     echo "testGlobalVar=$testLocalVar" >> $GITHUB_OUTPUT
    
    # - name: Accessing github output
    #   run: |
    #     echo ${{ steps.set_output.outputs.testGlobalVar }}
    #     echo "concatinating global var ${{ steps.set_output.outputs.testGlobalVar }}"

    - name: writing to html file
      run: |
        echo "in html file" >> ${{ env.test_file }}

    - name: Setting output to GITHUB_Summary
      id: set_summary
      run: |
        testLocalVar="hello i am the summary"
        echo "$testLocalVar" >> $GITHUB_STEP_SUMMARY
        echo "direct value to summary" >> $GITHUB_STEP_SUMMARY
        cat ${{ env.test_file }} >> $GITHUB_STEP_SUMMARY
        echo "ending value to summary" >> $GITHUB_STEP_SUMMARY

    - name: Setting output to GITHUB_Summary in same job different step
      id: set_summary_same_job
      run: |
        testLocalVar="hello i am the summary in same job just different step"
        echo "$testLocalVar" >> $GITHUB_STEP_SUMMARY

  build_two:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setting output to GITHUB_Summary 2
      id: set_summary2
      run: |
        testLocalVar="hello i am the summary 2"
        echo "$testLocalVar" >> $GITHUB_STEP_SUMMARY
