name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  cache_usage_report_file: cache_usage_report.html
  
jobs:
  cache_usage_calculate:
    runs-on: macos-latest

    outputs: 
      cache_size: ${{ steps.cache_size.outputs.CACHE_SIZE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: 'gradle'

      - name: Providing permissions
        run: chmod +x ./gradlew

      # - name: Start emulator, Run tests, Display cache usage
      #   uses: ReactiveCircus/android-emulator-runner@v2
      #   with:
      #     api-level: 31
      #     target: google_apis
      #     arch: x86_64
      #     script: |
      #       adb devices
      #       touch app/emulator.log
      #       chmod 777 app/emulator.log
      #       ./gradlew :app:connectedCheck --continue
      #       adb logcat -d | grep "Cache size" >> app/emulator.log &

      - name : Write logs
        id: cache_size
        run : |
          echo "CACHE_SIZE=$( echo "12-18 14:33:33.993 2803 2933 I System.out: ### Cache size First = 8.0K /data/data/com.example.cicddemoapp/cache" )" >> "$GITHUB_OUTPUT"
    
      - name : Run python script
        id: python_script
        run : |
          echo ${{ steps.cache_size.outputs.CACHE_SIZE }}
          chmod +x ./.github/scripts/formatCacheUsage.py
          python3 ./.github/scripts/formatCacheUsage.py ${{ steps.cache_size.outputs.CACHE_SIZE }}
     
      - name: Upload html file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.cache_usage_report_file }}
          path: ${{ env.cache_usage_report_file }}
          
  cache_usage_display:
    needs: cache_usage_calculate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.cache_usage_report_file }}

      - name: Add PR comment
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs')
            const cacheLogsFileContent = fs.readFileSync('cache_usage_report.html', 'utf8')
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: cacheLogsFileContent
            })
