name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Print base commit
      run: |
        echo ${{ github.event.pull_request.base.sha }}
        output = ${{ github.event.pull_request.base.sha }}
        echo $[$output:0:7]

    - name: Print head commit
      run: echo ${{ github.event.pull_request.head.sha }}

    - name: Print PR number
      run: echo ${{ github.event.number }}
